services:
  django:
    build: .
    container_name: django
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/1
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb


  pgdb:

    image: postgres
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    restart: always

  
volumes:
  pgdbdata: null
